apiVersion: v1
kind: Pod
metadata:
  name: rpsls-game-pod
  labels:
    app: rpsls-game
spec:
  containers:
    - name: rpsls-frontend
      image: rpsls-frontend:latest
      ports:
        - containerPort: 80
          hostPort: 8080
    - name: rpsls-backend
      image: rpsls-backend:latest
      ports:
        - containerPort: 8000
          hostPort: 8000
